"""Render a Report as human-readable Markdown or machine-readable JSON.

Issues are grouped by type so a 40-page crawl that's missing 40 titles reads as
one line with 40 URLs, not 40 near-identical entries.
"""

from __future__ import annotations

import json
from collections import defaultdict
from typing import Dict, List

from .checks import grade
from .model import (CRITICAL, NOTICE, SEVERITY_EMOJI, WARNING, Issue, Report)

# Short, stable headings for grouped findings.
LABELS = {
    "noindex": "Page set to noindex",
    "title_missing": "Missing <title>",
    "title_short": "Title too short",
    "title_long": "Title too long",
    "meta_desc_missing": "Missing meta description",
    "meta_desc_short": "Meta description too short",
    "meta_desc_long": "Meta description too long",
    "h1_missing": "Missing <h1>",
    "h1_multiple": "Multiple <h1> headings",
    "heading_skip": "Skipped heading levels",
    "canonical_missing": "Missing canonical tag",
    "canonical_offsite": "Canonical points off-site",
    "viewport_missing": "Missing viewport (mobile) tag",
    "lang_missing": "Missing html lang attribute",
    "img_alt_missing": "Images missing alt text",
    "img_alt_long": "Alt text too long",
    "thin_content": "Thin content",
    "og_missing": "Missing Open Graph tags",
    "mixed_content": "Mixed content on HTTPS",
    "page_heavy": "Heavy HTML page",
    "jsonld_invalid": "Invalid JSON-LD",
    "jsonld_no_type": "JSON-LD without @type",
    "jsonld_missing_fields": "Structured data missing fields",
    "jsonld_date_format": "Non-ISO date in structured data",
    "no_https": "Site not on HTTPS",
    "robots_missing": "No robots.txt",
    "robots_blocks_all": "robots.txt blocks everything",
    "robots_no_sitemap": "robots.txt has no sitemap",
    "sitemap_missing": "No sitemap.xml",
    "sitemap_invalid": "Invalid sitemap.xml",
    "dup_title": "Duplicate titles",
    "dup_meta": "Duplicate meta descriptions",
    "broken_link": "Broken internal links",
    "low_inlinks": "Pages with no internal links",
    "structured_data_coverage": "Low structured-data coverage",
}

_SECTIONS = [
    (CRITICAL, "Critical"),
    (WARNING, "Warnings"),
    (NOTICE, "Notices"),
]


def render_markdown(report: Report) -> str:
    c = report.counts()
    host = report.site_url or report.start_url
    lines: List[str] = []
    lines.append(f"# 🔍 SEO Audit — {host}")
    lines.append("")
    lines.append(
        f"**Score: {report.score}/100 ({grade(report.score)})**  ·  "
        f"🔴 {c[CRITICAL]} critical · 🟡 {c[WARNING]} warnings · 🟢 {c[NOTICE]} notices"
    )
    st = report.stats
    meta = (
        f"Crawled {st.get('pages_crawled', len(report.pages))} pages"
        f" · {st.get('links_checked', 0)} internal links checked"
    )
    if report.finished_at:
        meta += f" · {report.finished_at}"
    lines.append(meta)
    lines.append("")

    if not report.issues:
        lines.append("✅ No SEO issues found in the crawled scope. Nice.")
        lines.append("")

    for severity, heading in _SECTIONS:
        group = [i for i in report.issues if i.severity == severity]
        if not group:
            continue
        emoji = SEVERITY_EMOJI[severity]
        lines.append(f"## {emoji} {heading} ({len(group)})")
        lines.append("")
        lines += _render_group(group)

    lines += _render_pages_table(report)
    lines.append("")
    lines.append("---")
    lines.append("*Generated by [website-seo-audit](https://github.com/zxhydfzr/website-seo-audit) — 网站SEO诊断.*")
    return "\n".join(lines)


def _render_group(issues: List[Issue]) -> List[str]:
    by_code: Dict[str, List[Issue]] = defaultdict(list)
    order: List[str] = []
    for i in issues:
        if i.code not in by_code:
            order.append(i.code)
        by_code[i.code].append(i)

    out: List[str] = []
    for code in order:
        items = by_code[code]
        label = LABELS.get(code, code)
        suffix = f" ({len(items)}×)" if len(items) > 1 else ""
        out.append(f"### {label}{suffix}")
        out.append(f"{items[0].message}")
        if items[0].fix:
            out.append(f"- **Fix:** {items[0].fix}")
        for it in items[:12]:
            where = it.url if it.url else "site-wide"
            extra = f" — {it.detail}" if it.detail else ""
            out.append(f"- {where}{extra}")
        if len(items) > 12:
            out.append(f"- …and {len(items) - 12} more")
        out.append("")
    return out


def _render_pages_table(report: Report) -> List[str]:
    if not report.pages:
        return []
    # count issues per page url
    per_url: Dict[str, int] = defaultdict(int)
    for i in report.issues:
        if i.url:
            per_url[i.url] += 1
    out = ["## Pages crawled", "", "| URL | Status | Title len | Words | Issues |", "|---|---|---|---|---|"]
    for p in report.pages[:40]:
        status = p.status_code if p.status_code is not None else (p.fetch_error or "err")
        tlen = len(p.title) if p.title else 0
        out.append(f"| {p.url} | {status} | {tlen} | {p.word_count} | {per_url.get(p.url, 0)} |")
    if len(report.pages) > 40:
        out.append(f"| …and {len(report.pages) - 40} more | | | | |")
    return out


def render_json(report: Report) -> str:
    data = {
        "start_url": report.start_url,
        "site_url": report.site_url,
        "score": report.score,
        "grade": grade(report.score),
        "counts": report.counts(),
        "started_at": report.started_at,
        "finished_at": report.finished_at,
        "stats": report.stats,
        "robots": report.robots,
        "sitemap": report.sitemap,
        "issues": [
            {
                "severity": i.severity,
                "code": i.code,
                "message": i.message,
                "fix": i.fix,
                "url": i.url,
                "detail": i.detail,
            }
            for i in report.issues
        ],
        "pages": [
            {
                "url": p.url,
                "status": p.status_code,
                "final_url": p.final_url,
                "content_type": p.content_type,
                "title": p.title,
                "meta_description": p.meta_description,
                "h1_count": len(p.h1s),
                "word_count": p.word_count,
                "images": len(p.images),
                "internal_links": len(p.internal_links),
                "external_links": len(p.external_links),
                "jsonld_blocks": len(p.jsonld),
                "fetch_error": p.fetch_error,
            }
            for p in report.pages
        ],
    }
    return json.dumps(data, indent=2, ensure_ascii=False)
